### ISSUE TITLE
Outbox cleaner seems to not be implemented

### ISSUE THREAD

**Issue by kimbirkelund** [rebus-org/Rebus.SqlServer#108]
https://github.com/rebus-org/Rebus.SqlServer/blob/252881eb0e8728e644780e0174c1fa50fe09e193/Rebus.SqlServer/SqlServer/Outbox/OutboxForwarder.cs#L101-L104

Should this not be expanded upon? :-)

**Comment by mookid8000** [comment]
Oh yeah, it probably should.

Although I have begun to think that the whole "outbox" concept ought to be a separate project and not baked into your service bus.

The main reason being that your outbox is much more closely tied to whatever type of persistence you are using, and probably also to which library you are using, than to your "service bus outgoing messages needs".

Building an outbox as a separate project would also make it possible to enlist other types of tasks as "stuff that must be done when my transaction has been safely committed", e.g. generating PDFs in, POSTing/PUTing to idempotent HTTP endpoints, etc.

Thoughts?

**Comment by kimbirkelund** [comment]
I saw the outbox feature more for ensuring database updates and outgoing messages were all or nothing.

The examples you're quoting I would think would be better handled by sending a message.

But we've stopped using the outbox feature for now anyway, so not really critical for us after all :-)

**Comment by mookid8000** [comment]
Good 🙂 I'll probably publish an initial attempt at building a general outbox one of the following days. 😉
