### ISSUE TITLE
Add CreationTime timestamp

### ISSUE THREAD

**Issue by mookid8000** [rebus-org/Rebus.SqlServer#11]
because it is not possible to see the age of attachments that have not yet been read and might never be, which makes it hard to come up with a sensible way of removing these attachments.

**Comment by IsaacSee** [comment]
Added following pull request for this enhancement #18

**Comment by mookid8000** [comment]
Will be available in version 5.0.0 (which can be tried now in 5.0.0-b1)

**Comment by CzechsMix** [comment]
Is this just for databus? or is there a config option needed to turn this on?

I'm using Rebus.SqlServer 5.1 and I'm not seeing the CreationTime column in any of my queue tables.

**Comment by mookid8000** [comment]
That particular creation time can actually be had by parsing the headers, as it’s embedded there as `rbs2-sent-time`

Sendt fra min iPhone

–
Mogens Heller Grabe
Torsmark 4
8700 Horsens
Danmark

+45 29367077
mookid8000@gmail.com

**Comment by CzechsMix** [comment]
So if I wanted to do something like see all the messages sent in the last hour there's not a simple SQL Query I could execute?

If I'm not using the Defer functionality, is the 'visible' column essentially the same thing?

**Comment by mookid8000** [comment]
I think it is, yeah 🙂

Sendt fra min iPhone

–
Mogens Heller Grabe
Torsmark 4
8700 Horsens
Danmark

+45 29367077
mookid8000@gmail.com
