### ISSUE TITLE
How should the "priority" of messages be used ?

### ISSUE THREAD

**Issue by IsaacSee** [rebus-org/Rebus.SqlServer#12]
I noticed a "Priority" column on messages table but it seems that it is not really used. 
What should be the way to use it in order to process higher priorities first ?

**Comment by mookid8000** [comment]
It's an undocumented feature that the SQL transport can choose to use 😄 

Prioritizing messages is not really supported by any other transports, so the feature has no API in Rebus – but you can see [here](https://github.com/rebus-org/Rebus.SqlServer/blob/master/Rebus.SqlServer/SqlServer/Transport/SqlServerTransport.cs#L248-L258) that the SQL transport does in fact select its next message based on the priority in ascending order.

Only thing you need to do is to set the [`rbs2-message-priority`](https://github.com/rebus-org/Rebus.SqlServer/blob/master/Rebus.SqlServer/SqlServer/Transport/SqlServerTransport.cs#L36)  header to a number when you send the message, e.g. like this:

```csharp
var headers = new Dictionary<string, string> {
    {"rbs2-message-priority", "100"}
};

await bus.Send(work, headers);
```

to assign the priority 100 to the message.

---
sorry for not replying sooner, btw – I saw your message while I was on the move, and then I completely forgot about it!
