### ISSUE TITLE
Service broker-based transport

### ISSUE THREAD

**Issue by mookid8000** [rebus-org/Rebus.SqlServer#2]
@jeffreyabecker made a SQL Server Service Broker-based transport for Rebus. We should see if it is fit enough to be added to the Rebus.SqlServer package as an additional transport option.
- [ ] Create separate branch
- [ ] Pull in code from [here](https://github.com/jeffreyabecker/Rebus/tree/SqlServiceBus/Rebus.SqlServiceBroker)
- [ ] See if it works
- [ ] Create configuration extensions for it

**Comment by jeffreyabecker** [comment]
To answer your previous question, I haven't been using it. I originally wrote it hoping that it would resolve a CPU usage issue that my client has with the current sql transport but it doesn't help. It does work but hasn't had the couple months of usage that I'd like

**Comment by jeffreyabecker** [comment]
I may have project using it soon.

**Comment by majic79** [comment]
I have a desire to use SQL Server Service Broker queues - I'm not a fan of flat tables, so if I may, I can perhaps offer some feedback.

**Comment by mookid8000** [comment]
I'm going to close this one for now. Feel free to complain, if I should not have closed it 😁 

(a transport based on SQL Server Service Broker would still be nice.... just haven't had anyone make any requests for it for a couple of years now.....)
