### ISSUE TITLE
Async deadlock in EnsureTablesAreCreated

### ISSUE THREAD

**Issue by JornWildt** [rebus-org/Rebus.SqlServer#20]
In `SqlServerSagaStorage.cs` we have this little piece of code:

    void EnsureTablesAreCreated()
    {
      EnsureTablesAreCreatedAsync().Wait();
    }

Now we have a small WPF application for initial configuring of our main application. This config app is started as the first app ever on the database and thus becomes the app that creates the database tables for Rebus indirectly through `EnsureTablesAreCreated`.

Unfortunately WPF + synchronous Wait() result in a deadlock which means our little config app now deadlocks without ever creating the SQL server data tables (since it deadlocks before changes are commited to the database).

**Comment by mookid8000** [comment]
Good catch 👍 
It is fixed in 5.0.0-b2 which is out in a few minutes
