### ISSUE TITLE
In Transport "Receive" query, order by priority is ASC but should be DESC ?

### ISSUE THREAD

**Issue by IsaacSee** [rebus-org/Rebus.SqlServer#22]
https://github.com/rebus-org/Rebus.SqlServer/blob/3532abc977559b0bdc90e4bd8e37016ee87cadc2/Rebus.SqlServer/SqlServer/Transport/SqlServerLeaseTransport.cs#L143

Priority 100 should be handled before priority 0 right ?

**Comment by IsaacSee** [comment]
Same issue in SqlServerTransport.cs

**Comment by mookid8000** [comment]
> Priority 100 should be handled before priority 0 right ?

Not if priority is defined as "lower number means higher priority".

Did you come across some text somewhere that said how the priority is to be used?

**Comment by IsaacSee** [comment]
> Not if priority is defined as "lower number means higher priority". 😉
Ah for sure, but it does feels a bit unnatural no ? :)

**Comment by mollyporph** [comment]
In work-queue systems priority is normally descending since it allows for prioritized messaging. So if you're trying to build a system where you allow for manual manipulation of the priority, then a DESC would be the way to go.

**Comment by mookid8000** [comment]
Allright allright I'll change it! 😁 

In Rebus.SqlServer version 5 (from 5.0.0-b03 and onwards) HIGHER NUMBER means HIGHER PRIORITY.
