### ISSUE TITLE
High polling frequency due to parallelism configuration

### ISSUE THREAD

**Issue by maskati** [rebus-org/Rebus.SqlServer#26]
It seems that the SQL transport polling frequency is max parallelism (`SetMaxParallelism`) for each backoff interval rather than number of workers (`SetNumberOfWorkers`) for each interval. The default parallelism of 5 and backoff interval of 250ms results in 20 polls per second. Is there a way to reduce the polling frequency without sacrificing parallelism or latency?

**Comment by mookid8000** [comment]
Unfortunately, no - the parallelism is "true" this way, in that it extends all the way directly to the transport implementation. This is beneficial for most truly asynchronous transports, e.g. like Amazon SQS and Azure Service Bus, as this will allow for receiving at maximum rate even with one single worker thread.

However, the SQL transport is internally limited to 20 concurrent attempted receive operations via the `AsyncBottleneck` [seen here](https://github.com/rebus-org/Rebus.SqlServer/blob/master/Rebus.SqlServer/SqlServer/Transport/SqlServerTransport.cs#L64), so it will never go beyond 20 parallel polls.

I suggest you see if you can can by with a longer poll interval during backoff, e.g. configuring it to wait for maybe something like several seconds, after longer periods of inactivity.

Hopefully, you can find a good compromise between latency and polling activity this way.
