### ISSUE TITLE
Should `SqlServerTransport` use `ConfigureAwait(false)` ?

### ISSUE THREAD

**Issue by MrMDavidson** [rebus-org/Rebus.SqlServer#30]
Just looking through some of the code in Rebus.Sqlserver. I know in Rebus core's `ThreadPoolWorker` that it's using `ConfigureAwait(false)` for all it's async operations. However I notice that in `SqlServerTransport` (and the lease transport, too, I guess) this isn't the case.

Eg. https://github.com/rebus-org/Rebus.SqlServer/blob/db455fcca9ff7317a8169276250c7c35812b6f7f/Rebus.SqlServer/SqlServer/Transport/SqlServerTransport.cs#L288

Is there a reason why this isn't using `ConfigureAwait(false)` ?

**Comment by mookid8000** [comment]
> Is there a reason why this isn't using `ConfigureAwait(false)`?

No 😄 

It probably should.

**Comment by MrMDavidson** [comment]
Okay, just wanted to check there wasn't some big underlying reason for it before I looked into it further!

**Comment by mookid8000** [comment]
Fixed in 5.0.0-b7 😄
