### ISSUE TITLE
Bigint data type for id in the table for due messages

### ISSUE THREAD

**Issue by rsivanov** [rebus-org/Rebus.SqlServer#46]
Hi

SqlServerTimeoutManager creates a table with id defined as int.

 [id] [int] IDENTITY(1,1) NOT NULL

It seems that bigint would be a better choice for id as the table might be used in a production system with many inserts into due messages during many years. I had to make a fork of SqlServerTimeoutManager just to change data type for id.

**Comment by volodin-danila** [comment]
In addition to the SqlServerTimeoutManager, also SqlServerTimeoutsConfigurationExtensions and MathUtil. Not comfortable.

**Comment by mookid8000** [comment]
You're absolutely right – the ID should be a `BIGINT`

**Comment by mookid8000** [comment]
fixed by #47 – available in Rebus.SqlServer 5.1.0
