### ISSUE TITLE
Make ExpiredMessagesCleanupTask interval configurable

### ISSUE THREAD

**Issue by clegendre** [rebus-org/Rebus.SqlServer#60]
Hello,

I'm experiencing timeouts in ExpiredMessagesCleanupTask, so I dig into the code and noticed that ExpiredMessagesCleanupInterval is not used for ExpiredMessagesCleanupTask (which is hardcoded to 60 seconds).
Could you bind this configuration to the task, and make it more accessible via SqlServerTransportOption ?

Thanks you !

**Comment by mookid8000** [comment]
Thanks for reporting this 🙂  it's fixed in Rebus.SqlServer 6.0.1, which is on NuGet.org now 😁 

Thanks again! 👍
