### ISSUE TITLE
DateTimeOffset vs DateTime comparison

### ISSUE THREAD

**Issue by clegendre** [rebus-org/Rebus.SqlServer#63]
Hello,
At this line of code, the query of "expired lease" messages does not work since the code is comparing datetimeoffset vs datetime2. 

https://github.com/rebus-org/Rebus.SqlServer/blob/b41d2d8688d66f80395924567a023610cb725f13/Rebus.SqlServer/SqlServer/Transport/SqlServerLeaseTransport.cs#L142

**Comment by mookid8000** [comment]
Damn, that's a bug!

**Comment by mookid8000** [comment]
it's fixed in Rebus.SqlServer 6.1.1

Thanks for reporting the bug 🙂
