### ISSUE TITLE
Retrieve connection and transaction from IDbConnection

### ISSUE THREAD

**Issue by Rensvind** [rebus-org/Rebus.SqlServer#66]
Hi!

I was looking at the SqlAllTheWay sample since I wanted to make sure that rebus and my data persistence would share the same db connection/transaction. Looking at [IDbConnection](https://github.com/rebus-org/Rebus.SqlServer/blob/master/Rebus.SqlServer/SqlServer/IDbConnection.cs) I saw that there is a CreateCommand method. Is there a reason for just exposing CreateCommand and not SqlConnection and SqlTransaction? I guess I can get the connection and transaction from the SqlCommand but that seems a bit strange to do.

**Comment by mookid8000** [comment]
No other reason besides the fact that that made it convenient to use. 🙂

**Comment by Rensvind** [comment]
Is it ok if I make a pull request where I have exposed the SqlConnection and SqlTransaction in IDbConnection?

**Comment by mookid8000** [comment]
While that sounds like a small and innocent contribution, it introduces a breaking change to the `IDbConnection` interface, requiring that the major version is bumped and any custom implementations out there be changed accordingly.

I'd do a lot to avoid that 🙂 

I suggest you create an extension method like this:
```csharp
    public static class RebusDbConnectionExtension
    {
        public static (SqlConnection, SqlTransaction) GetConnectionAndTransaction(this IDbConnection connection)
        {
            if (connection == null) throw new ArgumentNullException(nameof(connection));

            using var command = connection.CreateCommand();

            return (command.Connection, command.Transaction);
        }
    }
```
and then you can
```csharp
var (sqlConnection, sqlTransaction) = dbConnection.GetConnectionAndTransaction();
```
wherever you need them...?
