### ISSUE TITLE
Faulty DbConnectionFactoryProvider?

### ISSUE THREAD

**Issue by pi3k14** [rebus-org/Rebus.SqlServer#72]
Can't see that the documentation and implementation of https://github.com/rebus-org/Rebus.SqlServer/blob/master/Rebus.SqlServer/SqlServer/DbConnectionFactoryProvider.cs is in sync.

* It is DbConnctionProvider that ensures MARS, not DbConnectionFactoryProvider
* IsolationLevel property is not used, hence 'Will use System.Data.IsolationLevel.ReadCommitted" by default on transactions, unless another isolation level is set with the "IsolationLevel" property' is not correct.

Is this class used under these assumptions in the code, and should be improved, or are this just leftovers from a copy of DbConnectionProvider that should be removed?

**Comment by mookid8000** [comment]
Ah I see! Thanks for pointing it out 🙂 I've fixed it in Rebus.SqlServer 7.1.3
