### ISSUE TITLE
Non-optimal index for receive

### ISSUE THREAD

**Issue by pi3k14** [rebus-org/Rebus.SqlServer#73]
Search for bus messages in SqlServerTransport are done with
`		WHERE	
                M.[visible] < sysdatetimeoffset()
		AND		M.[expiration] > sysdatetimeoffset()
		ORDER
		BY		[priority] DESC,
				[visible] ASC,
				[id] ASC
`
and the index is created as
`	[priority] ASC,
        [visible] ASC,
        [expiration] ASC,
	[id] ASC
`

the following index gives about 70% higher throughput in TestSqlTransportReceivePerformance (10000 messages) with my setup ( all run on local development machine)
`	[priority] DESC,
        [visible] ASC,
	[id] ASC,
        [expiration] ASC
`
(have not concluded if 'expiration' is needed)

I would suggest a code change :)

**Comment by seankearon** [comment]
We saw performance issues recently when an incident gave us a backlog of about 5,000,000 messages that needed to be processed.

Our DBA investigated and suggested exactly the same index change.  We applied the change and saw significant throughput improvements.

@pi3k14 - would you like to add a PR for this?  If not, then I'd be happy to do that.  Assuming that @mookid8000 agrees with this change? 😄

**Comment by pi3k14** [comment]
@seankearon feel free to create a PR, I was just waiting to see that I hadn't misunderstood something.

**Comment by seankearon** [comment]
Thanks, @mookid8000  🚀
