### ISSUE TITLE
NOCOUNT in message connection

### ISSUE THREAD

**Issue by Rensvind** [rebus-org/Rebus.SqlServer#79]
Hi!

Would it be possible to add a "SET NOCOUNT OFF" to the end of the query that fetches messages?
https://github.com/rebus-org/Rebus.SqlServer/blob/master/Rebus.SqlServer/SqlServer/Transport/SqlServerTransport.cs#L358-L380

We have implemented a solution inspired by your SQL ALL THE WAY sample so we use the transports sql connection for our work in the handlers. 

We are also using NPoco as our ORM and NPoco uses the same logic as you do in [SqlServerSagaStorage](https://github.com/rebus-org/Rebus.SqlServer/blob/master/Rebus.SqlServer/SqlServer/Sagas/SqlServerSagaStorage.cs#L355-L360) to make sure that what we update has the correct version. But since the command that fetches the message issues SET NOCOUNT ON NPoco never recieves the number of affected rows. 

I guess we could issue a SqlCommand in every handler that sets NOCOUNT OFF but figured I should ask here first.

**Comment by mookid8000** [comment]
oh yes, definitely! just a moment

**Comment by mookid8000** [comment]
it's fixed in Rebus.SqlServer 7.1.1, which is out on NuGet.org in a few minutes 🙂 

Thanks for making me aware of this problem 👍
