### ISSUE TITLE
Cant seem to use rebus.sqlserver (b4.0.0-b03) in Rebus 4.0.0.b06

### ISSUE THREAD

**Issue by jmkelly** [rebus-org/Rebus.SqlServer#8]
This was an oddity, not really something that needs to be fixed, but I just thought I would note it here in case someone else comes across it.

For some reason, in VS 2017 after I loaded the .net core version of Rebus and Rebus.SqlServer, Visual Studio did not see Rebus.SqlServer, and I couldn't hook up the transport.

After restarting VS, it all seemed to work as it should.

**Comment by mookid8000** [comment]
I have experienced something like this myself when installing multiple NuGet packages in succession.

When I installed them one at a time, trying to build the solution with compile errors and everything in between, it seemed to work as it should.

My guess is that VS2017 does not flush its in-mem project model to the .csproj file often enough, resulting in somehow "overwriting" what would become the `<PackageReference>` element in the .csproj file had it been saved.

Did you by any change first `Install-Package Rebus -pre` and then immediately after `Install-Package Rebus.SqlServer -pre`?

**Comment by jmkelly** [comment]
I did it via the GUI ticking include pre release, but pretty sure I did
install in the order you mentioned below.

**Comment by mookid8000** [comment]
> but pretty sure I did install in the order you mentioned

but did you save the project (either by explicitly saving it, or by building the project) between installing the two packages?

**Comment by mookid8000** [comment]
Closing it because it didn't really seem to be an issue 😄 

(if you disagree, please reopen or attach some more comments in here...)

**Comment by jmkelly** [comment]
Spot on, sorry, should have closed it out myself.
