### ISSUE TITLE
Transport fails on Rebus 6.4.0

### ISSUE THREAD

**Issue by Rensvind** [rebus-org/Rebus.SqlServer#81]
If updating to Rebus 6.4.0 the transport fails on the following
https://github.com/rebus-org/Rebus.SqlServer/blob/1f7c49fe44b052228d0227851f71964c3ab79f76/Rebus.SqlServer/SqlServer/Transport/SqlServerTransport.cs#L95
since the parameter intervalSeconds has been renamed to interval and has changed type from int to TimeSpan.

I have a [pull request](https://github.com/rebus-org/Rebus.SqlServer/pull/80) that fixes the issue.

**Comment by mookid8000** [comment]
aw bummer, sorry about that! I've released Rebus 6.4.1 where I've reverted this particular API change ... could you try that and see if it fixes your issue?
