### ISSUE TITLE
Question: Retrying message from error queue.

### ISSUE THREAD

**Issue by keithernet** [rebus-org/Rebus.SqlServer#87]
Hello,

Is there any reason that I cannot copy a message from the error queue directly to the input queue if I want to retry it after fixing the issue that resulted in the message ending up there in the first place?

Thanks!

**Comment by mookid8000** [comment]
No reason not to do it 🙂 

And in case the double negation dilutes the message:

It's totally alright to retry messages my moving them out of the error queue into the queue of the consumer where they failed.
